# -*- coding: utf-8 -*-
"""Data EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1RHPbtPuclbjAi2FA1idKAkCLE4zUZk
"""

import pandas as pd
df = pd.read_csv("/content/Amazon_Reviews.csv",on_bad_lines='skip', engine='python')
df

df.shape

df.isnull().sum()

df.info()

"""Since we only need 3 columns which is Rating, Review title and Review Text to train our model we remove all the other columns.

"""

df = df.drop(['Reviewer Name','Profile Link','Country','Review Count','Review Date','Date of Experience'], axis = 1)
df

df.isnull().sum()

df.info()

df = df.dropna()

df.isnull().sum()

df['Rating'].head()

"""Since we only need rating as 1, 2, 3 and so on we remove the extra text from this column."""

df['Rating'] = df['Rating'].str.extract(r'Rated (\d) out of 5 stars').astype(int)

df

print(f"Rating count : \n{df['Rating'].value_counts()}")

import matplotlib.pyplot as plt

df['Rating'].value_counts().plot.bar(color = 'orange')
plt.title('Rating Distribution Count')
plt.xlabel('Ratings')
plt.ylabel('Count')
plt.show()

print(f"Rating Value Count - Percentage distribution:  \n{round(df['Rating'].value_counts()/df.shape[0]*100,2)}")

# Filter for negative ratings
negative_reviews = df[df['Rating'].isin([1, 2])]

# Combine text
text = " ".join(review for review in negative_reviews['Review Text'].dropna())

# Generate wordcloud
from wordcloud import WordCloud
import matplotlib.pyplot as plt

wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

# Filter for positive ratings
positive_reviews = df[df['Rating'].isin([4, 5])]

# Combine all review texts
text = " ".join(review for review in positive_reviews['Review Text'].dropna())

# Generate wordcloud
from wordcloud import WordCloud
import matplotlib.pyplot as plt

wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

df.to_csv('/content/Amazon_Reviews_Cleaned.csv', index=False)

